name: 🐞 Issue Report # unique name for the issue form template. Must be unique from all other templates, including Markdown templates (mandatory).
# name: 🐞 :beetle: \U0001F41E Issue Report
description: Report a bug, error, or other inconsistent and/or unexpected behavior from this repository. # information about this template that will appear in the template chooser interface (required).
title: "[Bug]: <title>" # default title that will be pre-populated in the issue submission form (optional).
labels: ["Bug", "Needs Triage"] # labels that will automatically be added to issues created with this template (optional).
assignees: # individuals that will be automatically assigned to issues created with this template (optional).
  - <assignee>
body: # definition of the input types in the form (mandatory).
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to complete this report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.1 (Default)
        - 0.0.1
        - 1.0.0 (other env)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
